### PR TITLE
fix the problem with animated stickers(gif)

### PR DESCRIPTION
**Pull request by dalamudx**

### CODE REVIEW

**Comment by riolubruh** [comment]
Looks good.

**Comment by riolubruh** [comment]
Comment out line 3919 as this causes a double-message and I'll accept it.

**Review by riolubruh — CHANGES_REQUESTED** [review]
Comment out line 3919 as it causes the message to send twice.

**Comment by dalamudx** [comment]
> Comment out line 3919 as it causes the message to send twice.

Odd,the code works fine for me.
Enabled StickerBypass in YABDP4Nitro?I know it will send a static png and a gif when it is enabled.

**Comment by riolubruh** [comment]
I didn't have sticker bypass enabled in yabdp4nitro, but now it works without commenting out the line for some reason..?

**Review by riolubruh — COMMENTED** [review]
works now idk why it wasnt working for me before lol

**Pull request merged**
